POST http://localhost:8080/clients HTTP/1.1
Content-Type: application/json


{
    "name": "test",
    "email": "t@j.com"
}


###

POST http://localhost:8080/accounts HTTP/1.1
Content-Type: application/json

{
    "client_id": "aaaaaaaa-d196-468a-9ce8-0658b78d3e34"
}

###

POST http://localhost:8080/transactions HTTP/1.1
Content-Type: application/json

{
    "account_id_from": "aaaaaaaa-ad38-4c77-b6a4-dee97c24e36e",
    "account_id_to": "bbbbbbbb-f669-4044-8c21-a704ab57ffe3",
    "amount": 1
}